<?php

return [
    'Home' => 'Home',
    'Development' => 'Development',
    'Support' => 'Support',
    'Well done!' => 'Well done!',
    'Powered by aint framework' => 'Powered by aint framework',
    'You have successfully installed aint framework skeleton application.' => 'You have successfully installed aint framework skeleton application.',
    'aint framework official forum' => 'aint framework official forum',
    'The framework is currently at the stage of early prototyping thus any kind of help is seeked for and highly appreciated. To report bugs, suggest improvements and fundamental changes use the %sissue tracker%s. The source code of the framework, skeleton and quick start projects as well as the documentation are all %shosted on GitHub%s.' => 'The framework is currently at the stage of early prototyping thus any kind of help is seeked for and highly appreciated. To report bugs, suggest improvements and fundamental changes use the %sissue tracker%s. The source code of the framework, skeleton and quick start projects as well as the documentation are all %shosted on GitHub%s.',
    'There is just one support channel at the moment: the %saint framework web forum%s (based on Google Groups). Please refer all your suggestions, ideas, questions and any other kind of feedback to the forum.' => 'There is just one support channel at the moment: the %saint framework web forum%s (based on Google Groups). Please refer all your suggestions, ideas, questions and any other kind of feedback to the forum.',
    'AINT PHP FRAMEWORK' => 'AINT PHP FRAMEWORK',
    'aint framework skeleton application' => 'aint framework skeleton application',
    'Quick Start' => 'Quick Start',
];
